#!/bin/bash
# Common methode to install and configure a trac plugin library
# Author: jdum
# Date: 30 avril 2019
# Version 1.1
#-----------------------------------------------------------------------------------------------
# Configure the trac.ini logo
#
#-----------------------------------------------------------------------------------------------
# Configure specific plugins
# Once the trac project is generated
# Wrapper

_setTracIniPlugin()
{
  pluginName=$1
  found=0
   _mdbg 1  "-- Enter _setTracIniPlugin"
   _minf "Configure $pluginName with trac-admin"
    [ -f $TRAC_IN ] && sudo chown apache:apache $TRAC_INI
    for methodHandler in ${!METHODS_PLUGINS[@]}
    do
       sudo trac-admin "${PROJECT_DIR}" upgrade 2>&1 | tee --append $LOG_FILE >/dev/null
      _mdbg 2  "compare ${methodHandler} with ${pluginName}"
      if [ "${methodHandler}" == "${pluginName}" ]
      then
            _mdbg 2  "$pluginName will be be processed by ${METHODS_PLUGINS["${methodHandler}"]} methode"

            ${METHODS_PLUGINS["${methodHandler}"]}
            _installPluginPackage  "${pluginName}"
            found=1
      fi
    done
    [ "${found}" == "0" ] && _mnok "Invalid plugin name $pluginName found=$found"
    _mdbg 1  "-- Leave _setTracIniPlugin"
}
#-----------------------------------------------------------------------------------------------
_backupTracIni() #
{
   _mdbg 1  "-- Enter _backupTracIni"
   _minf "Backup $TRAC_INI"
   timeStamp=$(_getTimeStamp)
   tracIniCopy=${TRAC_INI}.${timeStamp}
   sudo cp ${TRAC_INI} ${tracIniCopy}           || _mnok " Pb copying  ${TRAC_INI} -> ${tracIniCopy}"
   _mok "Made a copy of trac.ini in ${tracIniCopy}"
   sudo chmod 666 ${tracIniCopy}               &&  _mdbg 1  "Change to 666 permission for ${tracIniCopy}"

   _mdbg 1  "-- Leave _backupTracIni"
}
#------------------------------------------------------------------------------------------------
#
#
_installPluginPackage()
{
  _mdbg 1  "-- Enter _installPluginPackage"
  pluginName=$1
  installType="easyinstall"
  #[ "$2" != "" ] &&  installType=$2
  _mdbg 2  "Enter _installPluginPackage"
  _mdbg 2  "$pluginName install with $installType"
  cd ${PROJECT_DIR}/plugins
  if [ "${PLUGINS_URL["${pluginName}"]}" == "core" ]
  then
        _minf "$pluginName is a core Trac plugin"
  else
        case  ${installType} in
          easyinstall)  _mdbg 2  "From $(pwd) will perform an $installType"
                         sudo easy_install -U -Z  ${PLUGINS_URL["${pluginName}"]}  2>&1 | tee --append $LOG_FILE >/dev/null && \
                        _mok "$pluginName has been installed with $installType "
          ;;
          svn) _mdbg 1  "From $(pwd) will perform an $installType"
               sudo mkdir $installType &&  _minf "Create plugin $installType plugin repo"
               _mdbg 1  "From $(pwd) will perform an $installType co"
               svn co ${PLUGINS_URL["${pluginName}"]} && _mok "$pluginName svn repo co"
               setupPath=$(find . -name setup.py)
               _mdbg 1  "Warning setupPath=$setupPath"
               cd $(dirname $setupPath)
               _mdbg 1  "Lauchning setup.py from $(pwd)"
               _mdbg 1  "From $(pwd) will perform : python setup.py install"
               sudo python setup.py install && _mok "${pluginName} installed the $installType way"

          ;;
          pip) _mdbg 1  "pip install"
          ;;
        esac
   fi
  _mdbg 1  "-- Leave _installPluginPackage"
return 0
}

#-----------------------------------------------------------------------------------------------
# ADD settings key+value in a section to the trac.ini bellow a section
# using a source file and putting the modification in the destination file_
_setOptionInTracIniSection()
{

 section="$1"    # e.g [components]
 key="$2"        # key = value
 value=$3
 _mdbg 6  "Enter _setOptionInTracIniSection"
 _mdbg 6  "$section $key $value to add to trac.ini"
sudo trac-admin ${PROJECT_DIR} config set "$section" "$key" "$value" 2>&1 > /tmp/$0.trac-admin  # && _minf "trac.ini modified with $key=$value added in $section"
if grep upgrade /tmp/$0.trac-admin 2>&1 >/dev/null
then

      sudo trac-admin "${PROJECT_DIR}" upgrade 2>&1 >/dev/null
fi
_mdbg 6  " Leave _setOptionInTracIniSection"
return 0
}
#-----------------------------------------------------------------------------------------------
